source "https://rubygems.org"

gem "jekyll", "~> 4.4"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
end

gem "webrick", "~> 1.9"

gem "just-the-docs", "~> 0.10.1"
gem 'jekyll-sass-converter', github: 'jekyll/jekyll-sass-converter', ref: '7dd53306b2046ff0fd213394563a3784aa207c16', branch: 'master' # https://github.com/sass-contrib/sass-embedded-host-ruby/issues/265
