source "https://rubygems.org"

gem "jekyll", "~> 4.4"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
end

gem "webrick", "~> 1.9"

gem "just-the-docs", "~> 0.11"
# gem 'jekyll-sass-converter', '~> 3.1.0' # https://github.com/sass-contrib/sass-embedded-host-ruby/issues/265
